export const MENU_LIST = [
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
  {
    id: "dashboard",
    name: "Painel",
    to: "/painel",
    testeId: "sidenav-dashboard",
    Icon: FaChartPie,
  },
];
